// <auto-generated>
//
// Written from catalogs/flags.json by generate-common-languages.py at the project root.
// Do not edit: change the catalogue and run that script. The build refuses to compile
// when this file no longer matches the catalogue it names below.
//
// catalogue-sha256: 8deb288062db8690c92acc6491be655f906f3fc6d9a842d5652d14018235ad6e
// </auto-generated>

namespace UnityGameTranslator.Common
{
    public static partial class Flags
    {
        public const int Width = 16;
        public const int Height = 11;

        /// <summary>Flag id, then one string per row, each character a palette key.</summary>
        private static readonly string[][] CataloguePixels =
        {
            new[] { "de", "kkkkkkkkkkkkkkkk", "kkkkkkkkkkkkkkkk", "kkkkkkkkkkkkkkkk", "kkkkkkkkkkkkkkkk", "rrrrrrrrrrrrrrrr", "rrrrrrrrrrrrrrrr", "rrrrrrrrrrrrrrrr", "rrrrrrrrrrrrrrrr", "yyyyyyyyyyyyyyyy", "yyyyyyyyyyyyyyyy", "yyyyyyyyyyyyyyyy" },
            new[] { "fr", "bbbbbwwwwwwrrrrr", "bbbbbwwwwwwrrrrr", "bbbbbwwwwwwrrrrr", "bbbbbwwwwwwrrrrr", "bbbbbwwwwwwrrrrr", "bbbbbwwwwwwrrrrr", "bbbbbwwwwwwrrrrr", "bbbbbwwwwwwrrrrr", "bbbbbwwwwwwrrrrr", "bbbbbwwwwwwrrrrr", "bbbbbwwwwwwrrrrr" },
            new[] { "gb", "bwwbbbbwwbbbbwwb", "bbwwbbbwwbbbwwbb", "bbbwwbbwwbbwwbbb", "rbbbwwwwwwwwbbbr", "wrrrrwwwwwwrrrrw", "wwwwwwrrrrwwwwww", "wrrrrwwwwwwrrrrw", "rbbbwwwwwwwwbbbr", "bbbwwbbwwbbwwbbb", "bbwwbbbwwbbbwwbb", "bwwbbbbwwbbbbwwb" },
            new[] { "in", "oooooooooooooooo", "oooooooooooooooo", "oooooooooooooooo", "wwwwwwwwwwwwwwww", "wwwwwwwbbwwwwwww", "wwwwwwbwwbwwwwww", "wwwwwwwbbwwwwwww", "wwwwwwwwwwwwwwww", "gggggggggggggggg", "gggggggggggggggg", "gggggggggggggggg" },
            new[] { "jp", "wwwwwwwwwwwwwwww", "wwwwwwwwwwwwwwww", "wwwwwwwrrwwwwwww", "wwwwwrrrrrrwwwww", "wwwwrrrrrrrrwwww", "wwwwrrrrrrrrwwww", "wwwwrrrrrrrrwwww", "wwwwwrrrrrrwwwww", "wwwwwwwrrwwwwwww", "wwwwwwwwwwwwwwww", "wwwwwwwwwwwwwwww" },
            new[] { "np", "ccc.............", "crcc............", "crwrcc..........", "crrrrcc.........", "crrrrrcc........", "ccccccccc.......", "crrrrrcc........", "crwwwrcc........", "crrrrrrcc.......", "crrrrrrrcc......", "cccccccccc......" },
            new[] { "se", "bbbbbyybbbbbbbbb", "bbbbbyybbbbbbbbb", "bbbbbyybbbbbbbbb", "bbbbbyybbbbbbbbb", "yyyyyyyyyyyyyyyy", "yyyyyyyyyyyyyyyy", "bbbbbyybbbbbbbbb", "bbbbbyybbbbbbbbb", "bbbbbyybbbbbbbbb", "bbbbbyybbbbbbbbb", "bbbbbyybbbbbbbbb" },
            new[] { "tr", "rrrrrrrrrrrrrrrr", "rrrrrrrrrrrrrrrr", "rrrwwwwrrrrrrrrr", "rrwwrrrwwrrrrrrr", "rrwrrrrrwrwrrrrr", "rrwrrrrrrwwwwrrr", "rrwrrrrrwrwrrrrr", "rrwwrrrwwrrrrrrr", "rrrwwwwrrrrrrrrr", "rrrrrrrrrrrrrrrr", "rrrrrrrrrrrrrrrr" },
        };

        /// <summary>Flag id, then key/#RRGGBB pairs. '.' is transparent and is never listed.</summary>
        private static readonly string[][] CataloguePalettes =
        {
            new[] { "de", "k", "#000000", "r", "#DD0000", "y", "#FFCE00" },
            new[] { "fr", "b", "#002654", "r", "#CE1126", "w", "#FFFFFF" },
            new[] { "gb", "b", "#012169", "r", "#C8102E", "w", "#FFFFFF" },
            new[] { "in", "b", "#000088", "g", "#138808", "o", "#FF9933", "w", "#FFFFFF" },
            new[] { "jp", "r", "#BC002D", "w", "#FFFFFF" },
            new[] { "np", "c", "#003893", "r", "#DC143C", "w", "#FFFFFF" },
            new[] { "se", "b", "#006AA7", "y", "#FECC00" },
            new[] { "tr", "r", "#E30A17", "w", "#FFFFFF" },
        };
    }
}
